# Open a new kitty window in the directory of the file. e.g., 
# > touch here.kitty
# then:
# (open)[/Path/to/here.kitty] in Obsidian will create a link to open a shell window.

protocol file
ext kitty
action launch --type=os-window --title=${FILE} "${SHELL}" -c 'cd "$(dirname "${FILE_PATH}")" && . "${FILE_PATH}"; exec "${SHELL}" -i'
